apiVersion: v1
kind: Service
metadata:
  name: obscured-truth-ui-lb
  namespace: obscured-truth
  labels:
    app: obscured-truth-ui-lb
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000
  selector:
    app: obscured-truth-ui

