export const PREFIX = 'Games:';

export const REGISTER_GAME = PREFIX + 'REGISTER_GAME';
export const START = PREFIX + 'START';
export const FETCH_GAME_BY_UUID = PREFIX + 'FETCH_GAME_BY_UUID';
export const FETCH_GAME_BY_PIN = PREFIX + 'FETCH_GAME_BY_PIN';
export const REGISTER_PLAYER = PREFIX + 'REGISTER_PLAYER';
export const CHOOSE_SUSPECT = PREFIX + 'CHOOSE_SUSPECT';
export const RECORD_FACTS = PREFIX + 'RECORD_FACTS';
export const DEDUCTION = PREFIX + 'DEDUCTION';
export const RESULTS = PREFIX + 'RESULTS';

export const REGISTRATION_SUCCESS = PREFIX + 'REGISTRATION_SUCCESS';
export const RESULTS_SUCCESS = PREFIX + 'RESULTS_SUCCESS';
export const SUCCESS = PREFIX + 'SUCCESS';

export const ERROR = PREFIX + 'ERROR';
